### ISSUE TITLE
[ARM] Build is failing for arm architecture

### ISSUE THREAD

**Issue by jay11ca39** [beling/bsuccinct-rs#6] opened 2024-08-13 06:30 UTC
I am doing cross compilation on my linux host machine for ARM architecture. 
But I am getting following error for bitm library: 

> cargo build --target=arm-unknown-linux-gnueabi

```
error[E0080]: evaluation of constant value failed
  --> /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/bitm-0.4.2/src/rank_select/select.rs:12:38
   |
12 | pub const BITS_PER_L1_ENTRY: usize = 1<<32;
   |                                      ^^^^^ attempt to shift left by `32_i32`, which would overflow

note: erroneous constant encountered
   --> /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/bitm-0.4.2/src/rank_select/select.rs:156:31
    |
156 |         *rank -= i as usize * BITS_PER_L1_ENTRY - unsafe{l1ranks.get_unchecked(i)};
    |                               ^^^^^^^^^^^^^^^^^

note: erroneous constant encountered
   --> /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/bitm-0.4.2/src/rank_select/select.rs:155:65
    |
155 |         let i = partition_point_with_index(&l1ranks, |v, i| i * BITS_PER_L1_ENTRY - *v <= *rank) - 1;
    |                                                                 ^^^^^^^^^^^^^^^^^

note: erroneous constant encountered
   --> /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/bitm-0.4.2/src/rank_select/select.rs:534:54
    |
534 |                     if ONE {ones[1] - ones[0]} else {BITS_PER_L1_ENTRY-(ones[1] - ones[0])},
    |                                                      
```

**Note:** 
When doing cross compilation for aarch64 it is building fine.

**Comment by jay11ca39** [comment] 2024-08-13 09:43
Hello @beling 
After changing >>32 to >> 31 as below shown it built fine... 


```
diff --git a/bitm/src/rank_select/mod.rs b/bitm/src/rank_select/mod.rs
index 4b9c894..3af403f 100644
--- a/bitm/src/rank_select/mod.rs
+++ b/bitm/src/rank_select/mod.rs
@@ -208,9 +208,9 @@ impl<S: SelectForRank101111, S0: Select0ForRank101111, BV: Deref<Target = [u64]>
         // then corresponding indices l1ranks and l2ranks are also not out of bound
         let mut r = (self.content.get(word_idx)? & n_lowest_bits(index as u8 % 64)).count_ones() as usize;
         let block_content = *unsafe{ self.l2ranks.get_unchecked(index/2048) };
-        r += unsafe{ *self.l1ranks.get_unchecked(index >> 32) } + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
+        r += unsafe{ *self.l1ranks.get_unchecked(index >> 31) } + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64

-        r += (((block_content >> (11 * (!block & 3))) >> 32) & 0b1_11111_11111) as usize;
+        r += (((block_content >> (11 * (!block & 3))) >> 31) & 0b1_11111_11111) as usize;

         //Some(r + count_bits_in(unsafe {self.content.get_unchecked(block * 8/*word_idx&!7*/..word_idx)}))
         Some(r + count_bits_in(unsafe {self.content.get_unchecked(word_idx&!7..word_idx)}))
@@ -220,7 +220,7 @@ impl<S: SelectForRank101111, S0: Select0ForRank101111, BV: Deref<Target = [u64]>
         let block = index / 512;
         let word_idx = index / 64;
         let block_content = *unsafe{ self.l2ranks.get_unchecked(index/2048) };
-        let mut r = *self.l1ranks.get_unchecked(index >> 32) + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
+        let mut r = *self.l1ranks.get_unchecked(index >> 31) + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
         r += (self.content.get_unchecked(word_idx) & n_lowest_bits(index as u8 % 64)).count_ones() as usize;

         //r += (((block_content>>32) >> (33 - 11 * (block & 3))) & 0b1_11111_11111) as usize;
diff --git a/bitm/src/rank_select/select.rs b/bitm/src/rank_select/select.rs
index 3e7f0df..97ac9bc 100644
--- a/bitm/src/rank_select/select.rs
+++ b/bitm/src/rank_select/select.rs
@@ -9,7 +9,7 @@ use crate::ceiling_div;

 use super::utils::partition_point_with_index;

-pub const BITS_PER_L1_ENTRY: usize = 1<<32;
+pub const BITS_PER_L1_ENTRY: usize = 1<<31;
```


But want to know what impact it will do on features ?

**Comment by jay11ca39** [comment] 2024-08-13 11:00
@beling 
Any suggestion on this ?

**Comment by jay11ca39** [comment] 2024-08-13 11:22
Hello @beling 
After changing >>32 to >> 31 as below shown it built. 


```
diff --git a/bitm/src/rank_select/mod.rs b/bitm/src/rank_select/mod.rs
index 4b9c894..3af403f 100644
--- a/bitm/src/rank_select/mod.rs
+++ b/bitm/src/rank_select/mod.rs
@@ -208,9 +208,9 @@ impl<S: SelectForRank101111, S0: Select0ForRank101111, BV: Deref<Target = [u64]>
         // then corresponding indices l1ranks and l2ranks are also not out of bound
         let mut r = (self.content.get(word_idx)? & n_lowest_bits(index as u8 % 64)).count_ones() as usize;
         let block_content = *unsafe{ self.l2ranks.get_unchecked(index/2048) };
-        r += unsafe{ *self.l1ranks.get_unchecked(index >> 32) } + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
+        r += unsafe{ *self.l1ranks.get_unchecked(index >> 31) } + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64

-        r += (((block_content >> (11 * (!block & 3))) >> 32) & 0b1_11111_11111) as usize;
+        r += (((block_content >> (11 * (!block & 3))) >> 31) & 0b1_11111_11111) as usize;

         //Some(r + count_bits_in(unsafe {self.content.get_unchecked(block * 8/*word_idx&!7*/..word_idx)}))
         Some(r + count_bits_in(unsafe {self.content.get_unchecked(word_idx&!7..word_idx)}))
@@ -220,7 +220,7 @@ impl<S: SelectForRank101111, S0: Select0ForRank101111, BV: Deref<Target = [u64]>
         let block = index / 512;
         let word_idx = index / 64;
         let block_content = *unsafe{ self.l2ranks.get_unchecked(index/2048) };
-        let mut r = *self.l1ranks.get_unchecked(index >> 32) + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
+        let mut r = *self.l1ranks.get_unchecked(index >> 31) + (block_content & 0xFFFFFFFFu64) as usize; // 32 lowest bits   // for 34 bits: 0x3FFFFFFFFu64
         r += (self.content.get_unchecked(word_idx) & n_lowest_bits(index as u8 % 64)).count_ones() as usize;

         //r += (((block_content>>32) >> (33 - 11 * (block & 3))) & 0b1_11111_11111) as usize;
diff --git a/bitm/src/rank_select/select.rs b/bitm/src/rank_select/select.rs
index 3e7f0df..97ac9bc 100644
--- a/bitm/src/rank_select/select.rs
+++ b/bitm/src/rank_select/select.rs
@@ -9,7 +9,7 @@ use crate::ceiling_div;

 use super::utils::partition_point_with_index;

-pub const BITS_PER_L1_ENTRY: usize = 1<<32;
+pub const BITS_PER_L1_ENTRY: usize = 1<<31;
```


But want to know what impact it will do on features ?

**Comment by beling** [comment] 2024-08-16 19:14
#5 is the same issue. Your patch is not correct, but it will probably work correctly for for small arrays, up to 2 to a power of 31 bits.

**Comment by jay11ca39** [comment] 2024-08-16 20:07
> #5 is the same issue. Your patch is not correct, but it will probably work correctly for for small arrays, up to 2 to a power of 31 bits.

Hi @beling 
Thanks for reply.. Yes it is same as #5
Is there any plan for ARM support ?

**Comment by beling** [comment] 2024-08-16 20:36
The problem is not "arch" but "32". I will try to fix the compilation on 32 bit platforms soon. However, a lot of code is optimized for 64 bit CPUs, and probably on 32 bit it won't run very efficiently.

**Comment by jay11ca39** [comment] 2024-08-18 03:28
> The problem is not "ARM" but "32". I will try to fix the compilation on 32 bit platforms soon. However, a lot of code is optimized for 64 bit CPUs, and probably on 32 bit it won't run very efficiently.

Will look forward for ARM 32-bit support.. Thank you..

**Comment by beling** [comment] 2024-08-21 09:52
I'm closing as duplicate of #5. Please conduct further discussion there.

**Closed by beling** 2024-08-21 09:52 UTC
